# Generated by Django 5.0.7 on 2024-08-12 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='classgroupenrollment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 11, 23, 38, 735161), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='passtag',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='passtagrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 11, 23, 38, 735161), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование'),
        ),
    ]
