# Generated by Django 5.0.7 on 2024-07-26 09:06

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_individual_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.AddField(
            model_name='individual',
            name='social_insurance_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[base.catalogs.models.individual.social_insurance_number_validator], verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
