# Generated by Django 5.0.7 on 2024-08-12 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_classgroup_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroupenrollment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='passtagrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
