# Generated by Django 5.0.7 on 2024-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_individual_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской'), ('-', 'Не указан')], default='-', max_length=1),
        ),
    ]
