# Generated by Django 5.0.7 on 2024-08-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_classgroupenrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование')),
                ('individual', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_employee', to='base.individual', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
