# Generated by Django 5.0.7 on 2024-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_individual_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Обучающийся'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('M', 'Мужской'), ('-', 'Не указан')], default='-', max_length=1, verbose_name='Пол'),
        ),
    ]
