# Generated by Django 5.0.7 on 2024-08-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основная')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Элемент списка должностей',
                'verbose_name_plural': 'Элементы списка должностей',
            },
        ),
    ]
