# Generated by Django 5.0.7 on 2024-07-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_individual_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='is_student',
        ),
    ]
