# Generated by Django 5.0.7 on 2024-08-23 11:23

import base.entities.catalogs.transport_pass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_positionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование')),
                ('pass_id', models.CharField(max_length=13, unique=True, validators=[base.entities.catalogs.transport_pass.models.pass_id_validator], verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Транспортная карта',
                'verbose_name_plural': 'Транспортные карты',
            },
        ),
    ]
