# Generated by Django 5.0.7 on 2024-07-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contacttype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactType',
            new_name='ContactInfoType',
        ),
    ]
