# Generated by Django 5.0.7 on 2024-07-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_contacttype_contactinfotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('contact_info_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.contactinfotype', verbose_name='Тип')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.individual', verbose_name='Физическое лицо')),
            ],
        ),
    ]
