# Generated by Django 5.0.7 on 2024-07-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contactinfoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfoitem',
            options={'verbose_name': 'Элемент контактной информации', 'verbose_name_plural': 'Элементы контактной информации'},
        ),
        migrations.AlterModelOptions(
            name='contactinfotype',
            options={'verbose_name': 'Тип контактной информации', 'verbose_name_plural': 'Типы контактной информации'},
        ),
    ]
