# Generated by Django 5.0.7 on 2024-07-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_contactinfoitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfoitem',
            name='contact_info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.contactinfotype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contactinfoitem',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.individual', verbose_name='Физическое лицо'),
        ),
    ]
