# Generated by Django 5.0.7 on 2024-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_contactinfoitem_contact_info_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
