# Generated by Django 5.0.7 on 2024-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_individual_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfoitem',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
