# Generated by Django 5.0.7 on 2024-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_contactinfoitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(choices=[('F', 'Женский'), ('М', 'Мужской'), ('-', 'Не указан')], default='-', max_length=1, verbose_name='Пол'),
        ),
    ]
