# Generated by Django 5.0.7 on 2024-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_individual_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
    ]
