# Generated by Django 5.0.7 on 2024-08-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_individual_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Значение пола',
                'verbose_name_plural': 'Значения пола',
            },
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пол'),
        ),
    ]
