# Generated by Django 5.0.7 on 2024-08-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_gender_alter_individual_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='base.gender', verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
