# Generated by Django 5.0.7 on 2024-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_individual_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
        ),
    ]
