# Generated by Django 5.0.7 on 2024-08-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
