# Generated by Django 5.0.7 on 2024-08-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_student', to='base.individual', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
    ]
