# Generated by Django 5.0.7 on 2024-08-09 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name='Параллель')),
                ('label', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Литера')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='ClassGroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
            ],
            options={
                'verbose_name': 'Зачисление обучающихся в классы',
                'verbose_name_plural': 'Зачисления обучающихся в классы',
            },
        ),
        migrations.CreateModel(
            name='ClassGroupEnrollmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.classgroup', verbose_name='Класс')),
                ('class_group_enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classgroupenrollment', verbose_name='Зачисление')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.student', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Элемент зачисления в класс',
                'verbose_name_plural': 'Элементы зачисления в класс',
            },
        ),
        migrations.CreateModel(
            name='ClassGroupEnrollmentRegistryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classgroup', verbose_name='Класс')),
                ('class_group_enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classgroupenrollment', verbose_name='Зачисление')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_group_enrollment_registry', to='base.student', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Элемент зачисления в класс (регистр)',
                'verbose_name_plural': 'Элементы зачисления в класс (регистр)',
            },
        ),
    ]
