# Generated by Django 5.0.7 on 2024-08-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_classgroup_classgroupenrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='individual',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='rel_student', to='base.individual', verbose_name='Физическое лицо'),
        ),
    ]
