# Generated by Django 5.0.7 on 2024-08-09 15:57

import base.objects.catalogs.pass_tag.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_student_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=9, unique=True, validators=[base.objects.catalogs.pass_tag.models.tag_id_validator], verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Чип',
                'verbose_name_plural': 'Чипы',
            },
        ),
        migrations.CreateModel(
            name='PassTagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='base.individual', verbose_name='Исполнитель')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester', to='base.individual', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка на чипы',
                'verbose_name_plural': 'Заявки на чипы',
            },
        ),
        migrations.CreateModel(
            name='PassTagRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Первоначальный', 'Первоначальный'), ('Замена утраченного', 'Замена утраченного'), ('Замена испорченного', 'Замена испорченного'), ('Дополнительный', 'Дополнительный'), ('Не указано', 'Не указано')], default='Не указано', max_length=50, verbose_name='Причина')),
                ('processing_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата обработки')),
                ('status', models.CharField(choices=[('Заявка', 'Заявка'), ('В работе', 'В работе'), ('Отклонено', 'Отклонено'), ('Выполнено', 'Выполнено')], default='Заявка', max_length=50, verbose_name='Статус')),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.individual', verbose_name='Держатель')),
                ('pass_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.passtag', verbose_name='Чип')),
                ('pass_tag_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.passtagrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Элемент заявки на чипы',
                'verbose_name_plural': 'Элементы заявки на чипы',
            },
        ),
    ]
