# Generated by Django 5.0.7 on 2024-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_passtag_passtagrequest_passtagrequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='label',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Литера'),
        ),
    ]
