# Generated by Django 5.0.7 on 2024-07-26 09:55

import pass_tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_tags', '0002_passcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcard',
            name='pass_id',
            field=models.CharField(max_length=9, validators=[pass_tags.models.pass_id_validator], verbose_name='Идентификатор'),
        ),
    ]
