# Generated by Django 5.0.7 on 2024-07-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_tags', '0004_passcardissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCardAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Действие с картами',
                'verbose_name_plural': 'Действие с картами',
            },
        ),
        migrations.AddField(
            model_name='passcardissue',
            name='description',
            field=models.CharField(default='', max_length=30, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passcardissue',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pass_tags.passcardaction'),
        ),
    ]
