# Generated by Django 5.0.7 on 2024-07-28 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_tags', '0008_alter_passcard_pass_type_alter_passcardissue_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcardissue',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оформления'),
        ),
    ]
