# Generated by Django 5.0.7 on 2024-07-29 17:36

import pass_tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_tags', '0010_alter_passcardaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcard',
            name='pass_id',
            field=models.CharField(max_length=9, unique=True, validators=[pass_tags.models.tag_id_validator], verbose_name='Идентификатор'),
        ),
    ]
