# Generated by Django 5.0.7 on 2024-07-30 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_contactinfoitem_comment'),
        ('pass_tags', '0012_remove_passcard_pass_type_passcardissue_card_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassCard',
            new_name='PassTag',
        ),
        migrations.RemoveField(
            model_name='passcardissue',
            name='action',
        ),
        migrations.RemoveField(
            model_name='passcardissue',
            name='card',
        ),
        migrations.RemoveField(
            model_name='passcardissue',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='passcardissue',
            name='individual',
        ),
        migrations.AlterModelOptions(
            name='passtag',
            options={'verbose_name': 'Чип', 'verbose_name_plural': 'Чипы.'},
        ),
        migrations.RenameField(
            model_name='passtag',
            old_name='pass_id',
            new_name='tag_id',
        ),
        migrations.CreateModel(
            name='PassTagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='base.individual', verbose_name='Исполнитель')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester', to='base.individual', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка на чипы',
                'verbose_name_plural': 'Заявки на чипы',
            },
        ),
        migrations.DeleteModel(
            name='PassCardAction',
        ),
        migrations.DeleteModel(
            name='PassCardType',
        ),
        migrations.DeleteModel(
            name='PassCardIssue',
        ),
    ]
