# Generated by Django 5.0.7 on 2024-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_tags', '0013_rename_passcard_passtag_remove_passcardissue_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passtag',
            options={'verbose_name': 'Чип', 'verbose_name_plural': 'Чипы'},
        ),
        migrations.AlterField(
            model_name='passtagrequest',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
    ]
