# Generated by Django 5.0.7 on 2024-07-30 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_individual_gender'),
        ('pass_tags', '0014_alter_passtag_options_alter_passtagrequest_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTagRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Первоначальный', 'Первоначальный'), ('Замена утраченного', 'Замена утраченного'), ('Замена испорченного', 'Замена испорченного'), ('Дополнительный', 'Дополнительный'), ('Не указано', 'Не указано')], default='Не указано', max_length=50, verbose_name='Причина')),
                ('processing_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('Заявка', 'Заявка'), ('Ожидает', 'Ожидает'), ('Выполнено', 'Выполнено'), ('Отклонено', 'Отклонено')], default='Заявка', max_length=50, verbose_name='Статус')),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.individual', verbose_name='Держатель')),
                ('pass_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pass_tags.passtag', verbose_name='Чип')),
                ('pass_tag_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_tags.passtagrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Элемент заявки на чипы',
                'verbose_name_plural': 'Элементы заявки на чипы',
            },
        ),
    ]
