# Generated by Django 5.0.7 on 2024-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_tags', '0016_alter_passtagrequestitem_pass_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtagrequestitem',
            name='status',
            field=models.CharField(choices=[('Заявка', 'Заявка'), ('В работе', 'В работе'), ('Отклонено', 'Отклонено'), ('Выполнено', 'Выполнено')], default='Заявка', max_length=50, verbose_name='Статус'),
        ),
    ]
