# Generated by Django 5.0.7 on 2024-07-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(max_length=9, verbose_name='Идентификатор')),
                ('pass_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pass_cards.passcardtype')),
            ],
            options={
                'verbose_name': 'Пропускная карта',
                'verbose_name_plural': 'Пропускные карты',
            },
        ),
    ]
