# Generated by Django 5.0.7 on 2024-07-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_individual_options_and_more'),
        ('pass_cards', '0003_alter_passcard_pass_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCardIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата оформления')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pass_cards.passcard')),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.individual')),
            ],
            options={
                'verbose_name': 'Оформление карты',
                'verbose_name_plural': 'Оформление карт',
            },
        ),
    ]
