# Generated by Django 5.0.7 on 2024-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_cards', '0005_passcardaction_passcardissue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcardissue',
            name='description',
            field=models.CharField(default='', max_length=30, verbose_name='Описание'),
        ),
    ]
