# Generated by Django 5.0.7 on 2024-07-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_individual_gender'),
        ('pass_cards', '0007_alter_passcard_pass_type_alter_passcardissue_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcard',
            name='pass_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pass_cards.passcardtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='passcardissue',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pass_cards.passcardaction', verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='passcardissue',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pass_cards.passcard', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='passcardissue',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.individual', verbose_name='Физическое лицо'),
        ),
    ]
