# Generated by Django 5.0.7 on 2024-07-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_cards', '0009_alter_passcardissue_issue_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passcardaction',
            options={'verbose_name': 'Действие с картами', 'verbose_name_plural': 'Действия с картами'},
        ),
    ]
