# Generated by Django 5.0.7 on 2024-07-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_cards', '0011_alter_passcard_pass_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passcard',
            name='pass_type',
        ),
        migrations.AddField(
            model_name='passcardissue',
            name='card_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pass_cards.passcardtype', verbose_name='Тип карты'),
        ),
    ]
