# Generated by Django 5.0.7 on 2024-07-29 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_remove_individual_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name='Параллель')),
                ('label', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Литера')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='base.individual', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
        migrations.CreateModel(
            name='ClassGroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classgroup', verbose_name='Класс')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_group_enrollments', to='classes.student', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Зачисление обучающегося в класс',
                'verbose_name_plural': 'Зачисления обучающихся в классы',
            },
        ),
    ]
