# Generated by Django 5.0.7 on 2024-07-28 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_individual_is_student'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classgroup', verbose_name='Класс')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.individual', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Зачисление обучающегося в класс',
                'verbose_name_plural': 'Зачисление обучающегося в класс',
            },
        ),
    ]
