# Generated by Django 5.0.7 on 2024-08-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_individual_patronymic'),
        ('classes', '0003_student_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='individual',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='base.individual', verbose_name='Физическое лицо'),
        ),
    ]
