# Generated by Django 5.0.7 on 2024-08-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_student_individual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroupenrollment',
            options={'verbose_name': 'Зачисление обучающихся в классы', 'verbose_name_plural': 'Зачисления обучающихся в классы'},
        ),
        migrations.RemoveField(
            model_name='classgroupenrollment',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='classgroupenrollment',
            name='student',
        ),
        migrations.CreateModel(
            name='ClassGroupEnrollmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classgroup', verbose_name='Класс')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='classes.student', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Элемент зачисления в класс',
                'verbose_name_plural': 'Элементы зачисления в класс',
            },
        ),
    ]
