# Generated by Django 5.0.7 on 2024-08-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classgroupenrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroupenrollmentitem',
            name='class_group_enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classgroupenrollment', verbose_name='Зачисление'),
        ),
    ]
