# Generated by Django 5.0.7 on 2024-08-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classgroupenrollmentitem_class_group_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroupenrollmentitem',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='class_group_enrollment_items', to='classes.student', verbose_name='Обучающийся'),
        ),
    ]
