# Generated by Django 5.0.7 on 2024-08-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_classgroupenrollmentitem_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroupenrollmentregistryitem',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classgroup', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='classgroupenrollmentregistryitem',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_group_enrollment_registry', to='classes.student', verbose_name='Обучающийся'),
        ),
    ]
